---
title: "ASRB"
author: "Zahid Asghar"
date: "3/18/2020"
output:
  html_document: 
    toc: yes
    toc_float: yes
  pdf_document: default
  word_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Item No.1

### Consideration of the Evaluation Reports in respect of Ms. Summaira Fayyaz, a PhD student, Department of Chemistry.**

    The Advanced Studies &amp; Research Board at its meeting held on 08.02.2012, approved the admission/ registration of Ms. Sumamaira Fayyaz, a PhD Scholar, Department of Chemistry and also appointed. Prof. Dr. Saqib Ali, as her Supervisor.

2. She joined the Department on 14.02.2012.

3. The Board at its meeting held on 18.08.2017, approved the following title of her thesis:-

  __&quot;Cationic Surfactants: Synthesis, Characterization, Micellization, Biological Behaviour and Drug Interaction&quot;__

4.  She has passed comprehensive Examination in August, 2015.

5. The Board at its meeting held on 08.01.2019, approved the grant of extension for one year i.e. upto 31.01.2020:-

6. Her paper was published in 2019.

7. She submitted her thesis on 02.12.2019.

8. The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-
 
    1.        Prof. Dr. H. G. Alt Lehrstuhl fur Anorganische Chemie II, Universitat Bayreuth, Anorganische-Chemisches Laboratorium,   Wacholderweg 27, 95445 Bayruth, Germany.

    2.        Dr. Ian s. Butler Professor, Department of Chemistry Otto Maass Building, Room 427, McGill University, 801 Sherbrooke Street West Montreal, Quebec, Canada H3A 0B8.

    3.       Prof. Dr. Saqib Ali  Supervisor,

9.  The reports of External Examiners are available at **Annexure-I to II,** whereas the report of the Supervisor is available at **Annexure-III.**

10. Section XI(f) of the Regulations relating to the Admission, Registration &amp; Examination in Ph.D. provides as under:-

  __&quot;If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.&quot;__

11. The case is placed before the Board for consideration.

                                                                           
## Item No.2

### Consideration of the Evaluation Reports in respect of Ms. Saba Ayub, a PhD. student in  Mathematics     
     
    The Advanced Studies &amp; Research Board at its meeting held on 05.09.2016, approved the admission/registration of Ms. Saba Ayub, PhD. student in Mathematics &amp; also appointed Dr. Waqas Mahmood as her Supervisor.

2. She joined the Department on 30.09.2016

3. She cleared Comprehensive Examination in September, 2017.

4. The Board at its meeting held on 02.09.2019, approved the following title of her Synopsis:-

  __&quot;A Study of Roughness in Different Algebraic Structures&quot;__

5. Her Paper was published in 2019.

6. She submitted her thesis on 30.09.2019.

7. The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-

    1.        Prof. Dr. Mehmet Ali OZTURK Adiyaman University Faculty of Arts and Sciences Department of Mathematics 02040 ADIY AMAN, Turkey

    2.        Prof. Dr. Brent Everitt Department of Mathematics University of York, York YO10 5DD U.K.

    3.        Dr. Waqas Mahmood Supervisor

8. The reports of External Examiners are available at **Annexure-I &amp; II** , whereas the report of the Supervisor is available at **Annexure-III.**

9. Section XI(f) of the Regulations relating to the Admission, Registration &amp; Examination in Ph.D. provides as under:-

  __&quot;If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.&quot;__

10. The case is placed before the Board for consideration.

## Item No.3
### Consideration of the Evaluation Reports in respect of Mr. Khalil-Ur-Rehman, a PhD student, Department of Mathematics.			 

    The Advanced Studies & Research Board at its meeting held on 03.02.2016, approved the admission/ registration of Mr. Khalil-Ur-Rehman, a PhD Scholar, Department of Mathematics and also appointed. Prof. Dr. Muhammad Yousaf Malik, as his Supervisor.
2. He joined the Department on 04.03.2016.
3. The Board at its meeting held on 13.12.2017, approved the following title of his thesis:-  
      __“Numerical solutions of stratified flows”__
4.	He has passed comprehensive Examination in August, 2016.
5.	His paper was published in 2019. 
6.	He submitted his thesis on 22.11.2019. 
7.	The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-
    1.	    Prof. Dr. Mustafa TURKYILMAZOGLU Hacettepe University, Faculty of Sciences, Department of Mathematics, 06532 BEYTEPE, ANKARA/Turkey.  

    2.	    Dr. Anjan Biswast Department of Physics, Chemistry & Mathematics Albama A&M University, Normal, Albama 35762, USA.
            
    3.      Prof. Dr. Muhammad Yousaf Malik Supervisor

8.	The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 
9.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
        __&quot;If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.&quot;__

10.	The case is placed before the Board for consideration.

## Item.No. 4
### Consideration of the Evaluation Reports in respect of Mr. Zahid Ahmed, a PhD student, Departments of Mathematics.					

      The Advanced Studies & Research Board at its meeting held on 05.09.2016, approved the admission/ registration of Mr. Zahid Ahmed, a PhD Scholar, Departments of Mathematics and also appointed. Prof. Dr. Sohail Nadeem, as his Supervisor.  
2. He joined the Department on 10.11.2016.
3. The Board at its meeting held on 06.12.2018, approved the following title of his thesis:-
    __&quot;Numerical Study of Two-Dimensional Flows of Nanofluids”&quot;__ 
    
4. He has passed comprehensive Examination in September, 2017.
5. His paper was published in 2018. 
6. He submitted his thesis on 22.11.2019. 
7. The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-
    1.      Prof. Dr. Chun-I Chen Professor, Department of Industrial Management, Dean, Office of Research and Development I-Shou University, No. 1, Sec. 1, Syuecheng   Rd.,Dashu District, Kaohsiung City 84001, Taiwan, R.O.C.
    2.      Prof. Dr. Guoqian Chen, Department of Mathematics College of Engineering,  Peking university, Beijing 100871, China.
    3.      Prof. Dr. Sohail Nadeem  Supervisor,

8. The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 
9. Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__
10. The case is placed before the Board for consideration.
 
## Item No. 5
### Consideration of the Evaluation Reports in respect of Mr. Muhammad Umair Sohail, a Phd student in Statistics

    The Advanced Studies & Research Board at its meeting held on 03.02.2016, approved the admission/ registration of Muhammad Umair Sohail, a PhD student in Statistics and appointed Prof. Dr. Javid Shabbir as his Supervisor.

2.	He joined the Department on 16.02.2016.

3.	He cleared Comprehensive Examination in April, 2017.

4.	The Board at its meeting held on 18.08.2017, approved the following title of his Synopsis and also appointed Prof. Dr. Sat Gupta  appointed as his Co-Supervisor:-
   __quot&;Study of Missing Values Under Different Imputation Methods.&quot;__

5.	His Paper was published in 2019.

6.	He submitted his thesis on 07.01.2020.

7.	The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:-  

    1.  Prof. Dr. Gamze OZEL KaDILAR 	Department of Statistics, Hacettepe University, 06800 BEYTEPE ANKARA/Turkey.
		
    2.  Prof. Dr. Myron Hlynka Department of Mathematics & Statistics University   of Windsor, Windsor, Ontario, Canada N9B 3P4. 
		
    3.  Prof. Dr. Javid Shabbir Supervisor

8.	The reports of External Examiners are available at Annexure-I & II, whereas the report of the Supervisor is available at Annexure-III.  
9.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

10.	The case is placed before the Board for consideration.

## Item No. 6
### Consideration of the Evaluation Reports in respect of Mr. Muhammad Imran, a PhD student, Department of Physics.				
        
        The Advanced Studies & Research Board at its meeting held on 04.02.2013, approved the admission/ registration of Mr. Muhammad Imran, a PhD Scholar, Department of Physics and also appointed. Prof. Dr. Nawazish Ali Khan, as his Supervisor.

2. He joined the Department on 130.02.2013.

3. The Board at its meeting held on 18.05.2016, approved the following title of his thesis:-
        __“Metal Doped Perovskites For Solar Cell Applications”__

4. He has passed comprehensive Examination in May, 2015.

5. His paper was published in 2017. 

6. Now Dean, Faculty of Social Sciences has approved, the following title of his thesis on 05.11.2018:-
    __“Highly Efficient and Stable Inverted Perovskite Solar Cells with Inorganic Charge Transport Layers.”__

7. He submitted his thesis on 30.04.2019. 

8.The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-  
 
    1.      Prof. Dr. Hyun-Tak Kim Principal Research/MIT-Center Head,  Metal-Insulator Transition (MIT) & Quantum Lab,  ETRI (Electronics & Telecommunicatin  Research Institute) 218 Gajeung-ro, Yuseong-gu, Daejeon, 34129, South Korea.
    2.      Prof. Dr. Bruce Hamilton Photon Science Institue Alan Turing Building The University of Manchester, M13 9PL, U.K.
    3.      Prof. Dr. Nawazish Ali Khan Supervisor,
             
9.	The reports of External Examiners are available at __Annexure-I to II__, whereas the report of the Supervisor is available at __Annexure-III__. 

10.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

11.   The case is placed before the Board for consideration.

## Item No.7
### Consideration of the Evaluation Reports in respect of Mr. Sajjad Ahmad, a PhD student, National Centre for Bioinfomatics.		

    The Advanced Studies & Research Board at its meeting held on 03.02.2016, approved the admission/ registration of Mr. Sajjad Ahmad, a PhD Scholar, National Centre for Bioinformatics and also appointed. Dr. Syed Sikandar Azam, as his Supervisor.

2. He joined the Department on 15.02.2016.

3. The Board at its meeting held on 06.12.2018, approved the following title of his thesis:-
    __“Deciphering the Dynamics of Therapeutic Proteins from Nosocomial Pathogens”.__

4. He has passed comprehensive Examination in January, 2018.

5. His paper was published in 2018. 

6. He submitted his thesis on 23.07.2019. 

7. The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-

    1.    	Prof. Dr. Burnella Franco Principal Investigator, Professor Of Medical Genetics Department of Translational Medicine, University of Nepales  “Federico II” TIGEM (Telethon Institute of Genetics and Medicine), Via Campi Flegrei 34, 80078 Pozzuoli, N (NA), Italy.
    2.	    Prof. Dr. Imre Berger School of Biochemistry, Biomedical Sciences, University of Bristol, 1 Tankard’s Close, Bristol BS8 1TD, U.K.

    3.	    Dr. Syed Sikandar Azam Supervisor,
                                     
8.	         The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 

9.	        Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

10.       The case is placed before the Board for consideration.

## Item No.8

### Consideration of the Evaluation Reports in respect of Mr. Fazal Akbar,            a  PhD. Student in Department of Biotechnology				

    The Advanced Studies & Research Board at its meeting held on 13.06.2013, approved the admission/ registration of Mr. Fazal Akbar, PhD Student in Department of Biotechnology. The board also appointed Prof. Dr. Zabta Khan Shinwari as his Supervisor.
2.  He joined the Department on 09.09.2013.
3.  He cleared comprehensive Examination on December, 2015.
4.	The Board at its meeting held on 18.08.2017, approved the following title of his thesis:-
    __“Genetic diversity and chemodiversity evaluation of Boswejjia saera populations.”__
5.	His paper was published in 2018.
6.	The Dean Faculty of Biological Sciences, dated 10.07.2018, approved the following _change in title of his thesis_:-
	__“Genetic Diversity and Chemodiversity Evaluation of Boswellia sacra Populations.”__

7.	He submitted his thesis on 23.08.2019.
8.	The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:-
	
    1.       Dr. Allan M. Showalter Professor and Chair, Ohio University Department of Environmental and Plant Biology Porter Hall, Room 504, Athens, OH 45701-2979, USA.
    2.       Dr. Nancy Connel Professor and Senior Scholar Department of Environmental Health and Engineering John Hopkins Bloomberg School of Public Health 621 Wast Pratt St, Ste, 210, Baltimore, MD 21202, USA. 
    3.       Prof. Dr. Zabta Khan Shinwari Supervisor,(Deptt.of Biotechnology)

9.	The reports of External Examiners are available at __Annexure-I to II__, whereas the report of the Supervisor is available at __Annexure-III__. 
10.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-
        __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

11.	The case is placed before the Board for consideration.
 
## Item.No.9
### Consideration of the Evaluation Reports in respect of Mr. Naseer Ahmed, a PhD student, Department of Biotechnology.					

    The Advanced Studies & Research Board at its meeting held on 20.02.2015, approved the admission/ registration of Mr. Naseer Ahmed, a PhD Scholar, Department of Biotechnology and also appointed. Dr. Muhammad Zia, as his Supervisor.
2. He joined the Department on 03.03.2015.

3. The Board at its meeting held on 16.01.2015, approved the following title of his thesis and Dr. Muhammad Adnan Saeed (NORI G-8/3, Islamabad) appointed, as his Co-Supervisor :- 
    __“Labeling of Clinically Significant Bio-Molecules with Tc-99m for Diagnostic Imaging New-Supervisor”.__

4.	He has passed comprehensive Examination in April, 2017.
5.	His paper was published in 2018. 
6.	He submitted his thesis on 30.08.2019. 
7.	The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-

    1.	    Prof. Dr. Timothy P. Durrett Department of Biochemistry and Molecular Biophysics, Kansas State University, 141 Chalmers Hall, 1711 Claflin Rd., Manhattan,  KS 66506, USA.
    2.	    Prof. Dr. Abdul R. Asif Institute of Clinical Chemistry/UMG-Laboratories University Medical Center Gottingen George-August-Univeristy, Robert-Koch-Str. 40, D-37075 Gottingen, Germany.
            
    3.      Dr. Muhammad Zia Supervisor,           

8.	The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 
10.	Section XI(f) of the Regulations relating to the Admission, Registration &  Examination in Ph.D. provides as under:-
    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

9.	The case is placed before the Board for consideration.

## Item No.10 
### Consideration of the Evaluation Reports in respect of Mr. Rashid Mehmood, a PhD. student in Biochemistry	.				

    The Advanced Studies & Research Board at its meeting held on 13.06.2013, approved the admission/registration of Mr. Rashid Mehmood, PhD. student in Biochemistry and also appointed Prof. Dr. Bushra Mirza as Supervisor & Dr. Farnaz Malik as his Co-Supervisor. 
2.	He joined the Department on 21.08.2013.

3.	He cleared Comprehensive Examination in December 2015.

4.	The Board at its meeting held on 28.07.2016, approved the following title of his thesis & Synopsis:-
    __“Isolation and Characterization of Biologically Active Compounds from Rhazya stricta and Evaluation of their Antidiabetic Activity.”__

5.	The Dean, Faculty of Biological Sciences has approved the following __change in title of his thesis__ on 28.02.2019:-
    __“Evaluation of Anti-diabetic Potential and Phytochemical Profiling of Rhazya stricta root"__

6.	His Paper was published in 2019.

7.	He submitted his thesis on 26.08.2019.

8.	The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:- 

    1.      Dr. Guillermo-I Perez-Perez Associate Professor, Department of Medicine NYU School of Medicine, NYU Longone Medical Center 8155 E Fairmount Dr. Apartment 1316 Denver CO 80230 USA 
    2.	    Prof. Dr. Brad Binder Department of Biochemistry & Cullular and Molecular Biology University of Tennessee, 309 Ken and Blaire Mossman Bldg., 1311 Cumberland Avenue, Knoxville, Tennessee 37996-1939 USA 
    3.	    Prof. Dr. Bushra Mirza Supervisor

9.	The reports of External Examiners are available at Annexure-I & II, whereas the report of the Supervisor is available at Annexure-III.  

10.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under 
      **If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”**

11.	The case is placed before the Board for consideration.**

## Item No.11
###  	Consideration of the Evaluation Reports in respect of Mr. Muhammad Junaid Dar , a PhD Student in Department of Pharmacy			

     The Advanced Studies & Research Board at its meeting held on 03.09.2015, approved the admission/registration of Mr. Muhammad Junaid Dar to PhD student in Pharmacy and also appointed Dr. Obaidullah as Supervisor & Prof. Dr. Gul Majid Khan as his Co-Supervisor. 

2.	He joined the Department on 17.09.2015.

3.  He cleared comprehensive Examination on December, 2016.

4.	The Board at its meeting held on 23.08.2017, approved the name of Prof. Dr. Gul Majid Khan, as Supervisor and Dr. Obaidullah as his Co-Supervisor.

5.	The Board at its meeting held on 07.11.2017, approved the following title of his thesis:-

    __“Design of Thiolated Polymer Coated Niosomes Gel: Promising Platform for Controlled and Targeted Drug Delivery in Leishmaniasis.”__

6.	The Dean Faculty of Biological Sciences, dated 14.02.2019, approved the following change in title of his thesis:-
   __“Formulation and evaluation of nano-elastic liposomes as multidrug carrier for the topical treatment of cutaneous liishmaniasis.”__

7.	His paper was published in 2019.

8.	He submitted his thesis on 03.10.2019.

9.	The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:- 

    1.     Prof. Dr. Claus-Michael Lehr Head. Dept. of Drug Deliver (DDEL) Helmholtz-Institute for Pharmaceutical Research Saarland (HIPS) Helmholtz Center for Infection Research (HZI) Saarland Uni;versity, Campus E8.1, 66123 Saarbrucken, Germany. 
    2.  	 Dr. Nessar Ahmed  Reader in Clinical Biochemistry  Centre for Bioscience, Department of Life Science Manchester Metropolitan University, Oxford Road, Manchester M1 5GD, U.K. 
    3.      Prof. Dr. Gul Majid Khan Supervisor

10.	The reports of External Examiners are available at Annexure-I to III, whereas the report of the Supervisor is available at Annexure-IV.   

11.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

    __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

12.	The case is placed before the Board for consideration.

## Item No.12 
  
### Consideration of the Evaluation Reports in respect of  Mr. Shahid Zaman, a PhD student in Microbiology.						

    The Advanced Studies & Research Board at its meeting held on 12.09.2012, approved the admission/registration in respect of Mr. Shahid Zaman to PhD in Microbiology. The Board also appointed Dr. Muhammad Imran as his Supervisor. 
    
2.	He joined the Department on 24.09.2012.

3.	The Board at its meeting held on 08.09.2014, approved the following title of his thesis:-
    __“Development of microbial based probiotic feed supplement and evaluation of its impact on growth, production and health of dairy cattle.”__

4.	He cleared Comprehensive Examination on August, 2014.

5.	His paper was accepted in 2019.

6.	He submitted his thesis on 30.08.2019.

7.  The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:-

    1.	    Dr. Mal Horsburgh, Staphylococcus Research Group, Room 302, Institute of Integrative Biology, Biosciences Building, University of Liverpool, Crown Street, Liverpool, L69 7ZB, U.K. 

    2.	    Prof. Dr. Marion DALMASSO Ur Abte EA 4651 – ER Malim Batiment M. Universite de Caen Normandie,Esplanade de la Paix, 14032 Caen Cedex, France. 
		
    3.	    Dr. Muhammad Imran     Supervisor   

8.	The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 

9.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

__“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

10.	The case is placed before the Board for consideration.

## Item No.13 

### Consideration of the Evaluation Reports in respect of Mr. Noor Hassan a PhD student, Department of Microbiology.				 

    The Advanced Studies & Research Board at its meeting held on 03.09.2015, approved the admission/ registration of Mr. Noor Hassan, a PhD Scholar, Department of Microbiology and also appointed. Prof. Dr. Fariha Hassan, as his Supervisor.
    
2. He joined the Department on 09.09.2015.

3. The Board at its meeting held on 25.05.2017, approved the following title of his thesis:-

  __“Diversity of Psychrophilic Bacteria from Different Glaciers of Karakoram Mountain Range (Pakistan) and their Potential for Production of Unsaturated/Saturated Fattay Acida”.__

4. The Board at its meeting held on 03.09.2015, approved the following change in title of his thesis:-

  __“Culturable Diversity of Psychrophilic Bacteria from Different Glaciers of Karakoram Mountain Range and role of Cell Memberane Fatty Acids in Cold Adaptation”.__
  
5. He has passed comprehensive Examination in October, 2018.

6. His paper was accepted in 2019. 
7. He submitted his thesis on 02.08.2019. 
8. The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:-

    1.      Prof. Dr. Geoffrey Michael Gadd Boyd Baxter Chair of   Biology Geomicrobiology Group, School of Life Sciences    University of Dundee, Dundee, DD1 4EH, Scotland, U.K.

    2.      Prof. Dr. Myron Hlynka Department of Mathematics and Statistics University of Windsor, Windsor, Ontario, Canada N9B 3P4.

    3.	   Prof. Dr. Fariha Hasan 
    Supervisor,

9. The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 

10. Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

__“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

11. The case is placed before the Board for consideration.

## Item No.14
### Consideration of the Evaluation Reports in respect of  Mr. Muhammad Jamshad Iqbal, a PhD. student in Plant Sciences.				
        	
    The Advanced Studies & Research Board at its meeting held on 19.8.2010, approved the admission/registration of Mr. Muhammad Jamshad Iqbal PhD. student in Plant Sciences & also appointed Dr. Riffat N. Malik as his Supervisor.
    
2.	He joined the Department on 23.09.2010.

3.	He cleared Comprehensive Examination in January, 2012.

4.	His Paper was published in 2012. 

5.	The Board at its meeting held on 21.06.2018, approved the following title of his Synopsis and granted extension for PhD thesis submission:-
Title of his Synopsis	Extension

  __Ecological and Genetic studies of Oriental White-backed Vulture (Gyps bengalensis) and Long-billed Vulture (Gyps indicus) in Pakistan	Till the end of Spring 2018__

6.	The Board at its meeting held on 06.12.2018 granted him extension till 31st January 2019. 

7.	The Dean, Faculty of Biological Sciences has approved the following change in title of his Synopsis on 27.12.2018:-
“Ecological studies of Oriental White-backed Vulture (Gyps bengalensis) and Long-billed Vulture (Gyps indicus) in Pakistan”.

8.	He submitted his thesis on 31.01.2019.

9.	The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of his thesis out of the panel approved by the Board:-

    1.	   Prof. Dr. Marco Festa-Bianchet Department de Biologies, Universite de Sherbrooke, Sherbrooke, Quebee J1 K 2R1, Canada.  
    
    2.	   Prof. Dr. Paul R. Krausman The Wildlife Society and John Hopkins University
    263 Camino Los Abuelos,Santa Fe, New Mexico 87508, USA. 
    
    3.	   Prof. Dr. Riffat N. Malik Supervisor

10.	The reports of External Examiners are available at Annexure-I & II, whereas the report of the Supervisor is available at Annexure-III.  

11.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

  __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

12.	The case is placed before the Board for consideration.

## Item No.15
### Consideration of the Re-evaluation Reports in respect of Mr. Basharat Ali, PhD Scholar, School of Politics & International Relations			

    The Advanced Studies & Research Board at its meeting held on 21.02.2013, approved the admission/ registration of Mr. Basharat Ali, PhD Scholar, School of Politics & International Relations, Dr. Mahmud-ul-Hassan as his Supervisor appointed.

2.  He joined the Department on 27.02.2013.

3.  He cleared comprehensive Examination on 17.02-2015.

4.	The Board at its meeting held on 18.08.2017, appointed Prof. Dr .Nazir Hussain as his Supervisor.

5.	The Dean, Faculty of Social Sciences approved the following change in title of his thesis on 29.08.2018:-

  __“Bureaucratic Politics in Foreign Policy Making: A Case Study of Pakistan’s Policy Towards Afghan Taliban 1996-2016.”__

6.	He submitted his thesis on 13.09.2018.

7.	His paper was accepted in 2019.

8.	The Vice Chancellor on the recommendations of the Director, SPIR appointed the following for the evaluation of her thesis out of the panel approved by the Board:-
    
    1.	  Prof. Dr. Gilles Boquerat 48 Rue Briant
    92260 Fontenay-Aux-Roses, France. 

    2.	  Prof. Dr. Arshin Adib-Moghaddam, Professor in Global Thought and Comparative Philosophies Chair, Centre for Iranian ;Studies Dept. of Politics and International Studies School of Oriental and African Studies (SOAS) University of London, Thornhaugh
    Street Russell Square, London WC1H IXG, UK. 
  
    3.      Prof. Dr. Nazir Hussain    Supervisor, (SPIR) 

9.	The Advanced Studies and Research Board at its meeting held on 19.02.2019, while considering the reports resolved as under:-

__“The Board after considering the reports of the referees and the supervisor resolved that the student should revise / rewrite the thesis in the light of the observations pointed out by the examiners in minimum six months’ time. The Board further resolved that the revised thesis be ensured by the supervisor that all comments / suggestions pointed out by the examiners are carried out by the student, which would be verified by the concerned Head of Department and the Dean of the Faculty. The revised thesis will be sent for re-evaluation to Prof. Dr. A. Gilles Boqerat, France and to third examiner for revaluation.”__ 

10.	In the light of the above decision of the Board now, Controller Examination has forwarded two reports i.e. one from Prof. Dr. A. Gilles Boqerat, France and one report from Prof. Dr. Arshin Adib-Moghaddam, available at (Annexure-I to Annexure-II) and Supervisor report available (Annexure-III) for reconsideration.

11.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

  __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

12.	The case is placed before the Board for re-consideration. 
 
## Item. No.16 

### Consideration of the Evaluation Reports in respect of Ms. Saima Syed, a PhD. student in Taxila Institute of Asian Civilizations.			

    The Advanced Studies & Research Board at its meeting held on 03.09.2015, approved the admission/registration of Ms. Saima Syed, PhD. student in TIAC. The Board also approved the following title of thesis and name of her Supervisor:-

    Title							                          Supervisor
  __Manuscriptology of Illuminated Qu’an: A__		 __Dr. Rafiullah Khan__
 __Collection of Gangh Bakhsh Library, Iran-Pakistan Institute of Persian Studies, Islamabad.__

2.	She joined the Institute on 16.09.2015.

3.	She cleared Comprehensive Examination on 28.11.2017.

4.	Her Paper was published in 2017.

5.	The Dean, Faculty of Social Sciences has approved the following change in title of her thesis on 15.02.2018:-

 __“Manuscriptology of Illuminated Manuscripts of Quran: AcCollection of Ganjbakhsh Library, Iran-Pakistan Institute of Persian Studies, Islamabad.”__

6.	She submitted her thesis on 26.09.2018.

7.	The Vice-Chancellor on the recommendations of the Director of the Institute, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-
	    
    1.	Prof. Dr. Carolyn Woodford Schmidt     95 South Parkview Avenue     (Northside Delivery, under Portico)     Columbus, Ohio 43209     United States of America 
    
    2.	Prof. Dr. Jennifer L. Campbell     1293 Westbrook Road     Kingston, Ontario, CANADA

    3.	Dr. Rafiullah Khan     Supervisor

8.	The reports of External Examiners are available at Annexure-I & II, whereas the report of the Supervisor is available at Annexure-III.  

9.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

__If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

10.	The case is placed before the Board for consideration.

## Item No.17
### Consideration of the Evaluation Reports in respect of Mr. Ansar Jamil, PhD Scholar, Department of Defence & Strategic Studies.			


    The Advanced Studies & Research Board at its meeting held on 06.09.2008 approved the admission/ registration of Mr. Ansar Jamil, PhD Scholar, Department of Defence & Strategic Studies an d also appointed Dr. Amir Waseem as his Supervisor.

2. He joined the Department on 27.10.2008.

3. He cleared comprehensive Examination 15.03.2011.

4. The Board at its meeting held on 11.04.2011, approved the name of Prof.            Dr. Rifaat Hussain, as his Supervisor. 

5. The Board at its meeting held on 20.10.2016, approved the following title of his thesis:-

 __“Caspian Sea Region: Great Powers’ Cooperation”.__
 
6.	The Board at its meeting held on 20.10.2016, granted him extension till 31.08.2017 .

7.	He submitted his thesis on 18.08.2017.

8.	His paper was published in, 2017.

9.	The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following examiners for the evaluation of his thesis out of the panel approved by the Board:-

    1.	Prof. Dr. S. Paul Kapur, Department of National Security Affairs
    Glasgow Hall U.S. Naval Postgraduate School Monterey, CA 93943, USA. 

    2.	Prof. Dr. Edward Newman School of Politics and International Studies University of Leeds Woodhouse Lane Leeds LS29JT, UK/Britain.

    3.  Prof. Dr. Rifaat Hussain 	 Supervisor
	
10.	The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 
11.	Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

  __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

12.	The case is placed before the Board for consideration.

## Item No.18

### Consideration of the Evaluation Reports in respect of Mr. Saad Ali Khan, a PhD student, Natioanal Institue of Pakistan Studies (NIPS).			

    The Advanced Studies & Research Board at its meeting held on 20.02.2015, approved the admission/ registration of Mr. Saad Ali Khan, a PhD Scholar, National Institute Pakistan and also appointed. Dr. M. Azam Chaudhary, as his Supervisor. 

2. He joined the Department on 02.03.2015. 

3. The Board at its meeting held on 20.02.2015, approved the following title of his thesis:-

  __“Religious pluralism in South Asian Sufi Tradition”.__
  
4. The Board at its meeting held on 07.11.2017, approved the following change in title of his thesis:-

  **Female Spiritual Authority and guidance: contemporary women Sufis in Pakistan.**

5. He has passed comprehensive Examination in 13.11.2017.

6. His paper was published in 2018. 

7. He submitted his thesis on 30.07.2019. 

8. Now Dean, Faculty of Social Sciences has approved the following title of his thesis on 18.06.2019:-

  __“Contemporary Sufi Shaykhas in Pakistan: Leaders, Discourses, communities and Practices.”__
  
9. The Vice Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-

    1.	Prof. Dr. Martin Sokefeld Institut Ethnologie Ludwing-Maximilians-Universitat Munchen, OettingenstraBe 67, 80538 Munchen, Germany. 
    
    2.	Prof. Dr. Francis Robinson, 22 Egham Hill, Egham, Surrey, UK TW20 0BD. 
    
    3.   Dr. Muhammad Azam Chaudhary      Supervisor,

10. The reports of External Examiners are available at Annexure-I to II, whereas the report of the Supervisor is available at Annexure-III. 

11. Section XI(f) of the Regulations relating to the Admission, Registration & Examination in Ph.D. provides as under:-

  __“If the thesis is adjudged as adequate by two of the three examiners, the Research Board shall allow the candidate to appear in the viva-voce (thesis defence) examination.”__

12. The case is placed before the Board for consideration.

## Item No.19 
###	Consideration of a case regarding grant of permission for conducting Viva-Voce (within three months’ time) in respect of Ms. Sarah Basharat, a PhD. student Health Services Academy						
        	
    The Advanced Studies & Research Board at its meeting held on 14.04.2015, approved the admission/registration of Ms. Sarah Basharat, PhD. student in Health Services Academy. The Board also approved the following title of thesis and name of her Supervisor:-

    Title							Supervisor

 __"Community Driven, Integrated Primary Dental Care"__	 __Dr. Babar Tasneem Sheikh	__

2.	She joined the institute on 09.02.2015.

3.	She cleared Comprehensive Examination on 13.12.2017 and delivered Seminar on 03.11.2017.

4.	The Dean, Faculty of Medicine has approved the following change in title of her thesis on 03.09.2018:-

  __“Integrating Oral Cancer Screening at the Primary Health Care Level in Pakistan-Assessing the Need, Rational and Modalities”.__

6.	Her Paper was published in 2018.

7.	She submitted her thesis on 04.09.2018.

8.	The case regarding Evaluation Reports was placed before the Board at its meeting held on 11.02.2020, wherein it was resolved as under:-

 __“The Board after considering the reports of the referees and the supervisor resolved that the student should revise / rewrite the thesis in the light of the observations pointed out by the examiners within three months’ time. The Board further resolved that the revised thesis be ensured by the supervisor that all comments / suggestions pointed out by the examiners have been carried out by the student, which would be verified by the concerned Head of Department and the Dean of the Faculty.”__
 
9.	In the light of the above decision of the Board now, the Assistant Controller (Secrecy) has forwarded (Annex-I)  the case and stated that Ms. Sarah Basharat has already submitted the revised thesis incorporated all comments/suggestion pointed out by the examiners and duly verified by the concerned Head of Department and Dean of the Faculty.

10.	The case is placed before the Board for re-consideration.

## Item No.20 

### Consideration of a case forwarded by the Incharge, Department of Anthropology regarding conversion of PhD admission in to M.Phil and allotment of registration number and issuance of new DMC M.Phil Viva Voce in respect of  Ms. Sajida Iffat, a PhD student in Anthropology.	
			
    The Advanced Studies & Research Board at its meeting held on 07.01.2005, approved the admission/registration in respect of Ms. Sajida Iffat to PhD in Anthropology. 

2.	She joined the Department on 21.02.2005.

3.	The Board at its meeting held on 05.06.2007, approved the following title of thesis and name of her Supervisor / Co-Supervisor:-

    Title 	Supervisor

 __"Effect of Modernity and Social Change on the Communities of Kalash Valley"	Dr. S. Anwar Iqbal".__

4. The Board at its meeting held on 06.09.2012, granted her extension upto Fall semester 2012.

5. She cleared Comprehensive Examination on 21.06.2007.

6. The condition of one compulsory research paper was not applicable to the scholar.

7. She submitted her thesis on 29.01.2013.

8. The Vice-Chancellor on the recommendations of the Chairperson of the Department, appointed the following for the evaluation of her thesis out of the panel approved by the Board:-

    1.	Prof. Dr. James W. Green, Senior Lecturer, Anthropology 353100 University of Washington, Seattle, WA 98195, USA. 
    
    2.	Prof. Dr. Brain Spooner University of Pennsylvania, Penn Museum, Room 508, 3260 South Street Philadelphia, PA 19104-6398, USA. 
    
    3.	Prof. Dr. Wenonah Lyon 8 Heaton Road Cantebbury, Kent CTI 2PY, U.K. 
    
    4.	Dr. Syed Anwar Iqbal Supervisor 
    
9.	The Advanced Studies and Research Board at its meeting held on 28.07.2016, while considering her Evaluation Reports resolved as under:-

 __“After considering the reports of the external examiners the Board did not accept the thesis for conducing viva-voce in respect of Ms. Sajida Iffat, a PhD student of Anthropology.”__

10.	The case was again placed before the Advanced Studies and Research Board at its meeting held on 18.08.2017, wherein it was resolved as under:-
	
	__“The Board rejected the case”__
	
11.	To re-consider the request of Ms. Sajida Iffat the Advanced Studies and Research Board at its meeting held on 05.06.2018, resolved as under:-

 __“The Board did not accede to the request of Ms. Sajida Iffat, a PhD student in Anthropology.”__

12.	The case regarding the Order dated 22.11.2019 passed by the Chief Justice Islamabad High Court was placed before the Board at its meeting held on 11.12.2019, wherein it was resolved as under:-

 __“The Board discussed the case at length on the directives of the Islamabad High Court and noticed that since one examiner had accepted the thesis whereas the two had rejected. In accordance with the prevailing rules she cannot be given ant concession except to award the M.Phil Degree in Anthropology after conducting the Viva-Voce Examination”.__

 13.	A similar case of Ms. Mehrine Rehman to PhD Chemistry was placed before the AS&RB held on 30.07.2008, wherein it was resolved to approve the recommendations of the Committee constituted by the Board and converted the PhD admission into MPhil in respect of respect of Ms. Mehrine Rehman, Department of Chemistry. The Board further asked the candidate to submit her M.Phil thesis in six months time, and no further extension shall be granted. Detail available at Annexure-I

14.	The case is placed before the Board for consideration.

## Item No.21 

### Consideration of the case forwarded by the Establishment Section regarding approval of the award of Post-doctoral Fellowship in respect of Dr. Saira Tabassum, in the Department of Chemistry.			

    Dr. Saira Tabassum, Ph.D in Biotechnology has submitted her application for Post Doc Research Fellowship in the Department of Chemistry under the supervision of Dr. Zia-ur-Rehman, Associate Professor of Chemistry. The Chairperson, Deptt. of Chemistry and the Dean Faculty of Natural Sciences have recommended her appointment as Postdoc Fellowship. 

2.	In this connection it is submitted that the relevant clause –Rules relating to award of Post-Doctoral Research Grants provide as under: 

Award of the Post-Doctoral Fellowship

 __“On receipt of the application, the Dean Faculty shall seek the advice of the Chairman (Chairperson) of the Department concerned and shall process the application for presentation to the Advance Studies and Research Board__ 
 __The Vice-Chancellor, after receiving recommendation from the Advance Studies and Research Board, Shall finally approve the award of Fellowship.__ 
 __The Registrar shall notify the letter of award clearly stating the terms of the award”.__

3.	The Vice-Chancellor has allowed to place the case before the Advanced Studies and Research Board. 

4.	The case is placed before the Board for consideration.

## Item No.22
### Consideration of a case regarding restoration of admission & change of Supervisor in respect of Ms. Zakia Batool, student Department of Statistics.									 

    The case regarding restoration of admission & change of Supervisor in respect of Ms. Zakia Batool, student Department of Statistics was placed before the Board at its meeting held on 11.02.2020, wherein it was resolved as under:-

 __“The Board resolved to approve the restoration of admission of PhD in respect of Ms. Zakia Batool, student at Department of Statistics. It was further resolved to refer the case to Dean, Faculty of Natural Sciences for allocation / assigning of supervisor.__
 __The Board took a serious note of allegations leveled against the Chairman, Department of Statistics who happened to be her supervisor and resolved to refer the case to University Harassment Committee for investigation as per THE PROTECTION AGAINST HARASSMENT OF WOMEN AT THE WORKPLACE ACT 2010 duly adopted by the University.__
 __The Board further resolved to constitute a Committee under the Chairmanship of Dean, Faculty of Natural Sciences along with Director, Quality Enhancement Cell to dig out the facts regarding cancellation of her admission based on the progress report.”__

2.	In the light decision of the AS&RB, now Dean, Faculty of Natural Sciences has forwarded the case of Ms. Zakia Batool, student Department of Statistics regarding restoration of admission & change of Supervisor. Detail mentioned is available at Annexure-I.

3.	The case is placed before the Board for consideration.


## Item No.23
### Consideration of a case forwarded by the Dean, Faculty of Natural Sciences regarding plea to the response of unsatisfactory report of Ms. Saba Kousar, 3rd M.Phil student in Electronics.				
 
    The Advanced Studies & Research Board at its meeting held on 01.10.2018, approved the admission/registration of Ms. Saba Kousar, student of M.Phil in Electronics. 

2.	She joined the Department on 09.10.2018.

3.	The Board at its meeting held on 11.12.2019, appointed Dr. Qurrat ul Ain as her Supervisor.

4.	The Dean, Faculty of Natural Sciences has forwarded a case of Ms. Saba Kousar, 3rd M.Phil student in Electronics regarding plea in response to unsatisfactory report. Detail mentioned is available at Annexure-I. 
 
5.	The case is placed before the Board for consideration.
 

## Item No. 24
		          
### Consideration of the case forwarded by the Chairperson, Department of Electronics regarding restoration of PhD admission of Mr. Abid Ali, ex- student Department of Electronics						

    Clause III(a-b-c) of the Regulations relating to re-admission, registration & examination to PhD provides as under:-

 __(a)	A student whose admission is cancelled on grounds other than disciplinary action may be re-admitted in the PhD Programme, subject to the payment of outstanding dues__

 __(b)	If the course work and comprehensive examination were passed within five years prior to the cancellation of the admission, full credit may be allowed regarding course work and comprehensive examination as the case may be. In case the admission is sought after the lapse of five year from the date of passing the course work and comprehensive examination the departmental PhD Admission Committee may determine the course(s) to be re-done as well as its recommendations about the comprehensive examination__
 
 __(c)	If a student who is re-admitted to PhD program and had previously spent the minimum period of three years as a PhD student, he/she may be allowed to submit the thesis after six months from the date of his/her re-admission.__
 
2. The Advanced Studies & Research Board at its meeting held on 08.01.2019, approved the cancellation of admission of Mr. Abid Ali, a PhD student in Electronics.

3.	The Chairperson, Department of Electronics (through Dean concerned) has forwarded the application of Mr. Abid Ali for restoration of PhD Admission in Electronics. Detail is available at Annexure-I

4.	The case is placed before the Board for consideration.

## Item No.25
###	Consideration of the recommendations of the Chairperson, Department of Chemistry regarding appointment of Co-Supervisor in respect of                    Mr. Muhammad Zubair, a PhD student in Chemistry			

    The Advanced Studies & Research Board at its meeting held on 13.02.2017, approved the admission/registration of Mr. Muhammad Zubair to PhD in Chemistry and also appointed Prof. Dr. Saqib Ali as his Supervisor. 
    
2.	He joined the Department on 21.02.2017.

3.	The Chairperson, Department of Chemistry (through Dean concerned) has forwarded (Annexure-I) the name of Dr. Sajjad Ahmad, Chief Scientific Officer as his Co-Supervisor.

4.	C.V. of Co-Supervisor is attached at Annex-II.

5.	The case is placed before the Board for consideration

## Item No.26
###	Consideration of the recommendations of the Chairperson, Department of Earth Sciences regarding appointment of Supervisor in respect of                 Mr. Abdul Wahab Khan, student of M.Phil in Earth Sciences.		

    The Advanced Studies & Research Board at its meeting held on 01.10.2018, approved the admission/registration, in respect of Mr. Abdul Wahab Khan, student of M.Phil in Earth Sciences.

2.	He joined the Department on 02.10.2018.

3.	The Chairperson, Department of Earth Sciences through Dean Faculty of Natural Sciences has proposed the name of Dr. Aamir Ali as Supervisor of Mr. Abdul Wahab Khan, student of M.Phil in Earth Sciences. 

4.	The case is placed before the Board for consideration.

## Item No.27
	
### Consideration of a case forwarded by the Director, School of Economics regarding the request of Mr. Farooq Rasheed for revival of enrollment status in PhD program.							
 
    The Director, School of Economics through Dean, Faculty of Social Sciences has forwarded the  request of Mr. Farooq Rasheed for revival of enrollment status in PhD program in Economics (Annex-I) and intimated that:-

 __“I had joined the PhD program at School of Economics in Fall-2007.            I completed the required coursework, cleared the comprehensive exam and defended the thesis proposal successfully.__
 __By November 2017, may thesis was ready for presentation in the Seminar at School of Economics, however due to a new ‘maximum 8-year duration policy to complete PhD’ of the HEC, I was not allowed to submit the thesis. On January 22,2018, I submit and application for the extension of my PhD enrollment and its was also not approved by AS&RB__
 __The ‘eight year’ duration of my admission in PhD at School of Economics was completed in Spring-2015 semester. I was granted extension in my PhD enrollment till Fall-2017 semester and I was regularly paying all the QAU dues till Fall-2017 semester__
 __However, I have recently read the notification of HEC (copy attached with ref:AD-QA/HEC/NQAC(21)/2016 according to which the new policy was meant for the PhD students admitted after issuance of the letter in 2016.__
 __In the light of above observations I would like to request you that my enrollment status in PhD in School of Economics may kindly be revived and I may be allowed to present the thesis in the School  seminar and then to submit it to the university for evaluation.”__

2.	The Vice-Chancellor has desired to place the case before AS&RB for consideration  


## Item No.28

### Consideration of the recommendations of the Director, Taxila Institute of Asian Civilization regarding appointment of Co-Supervisor in respect of                    Mr. Nafees Ahmed, a PhD student in TIAC					

    The Advanced Studies & Research Board at its meeting held on 20.02.2015, approved the admission/registration of Mr. Nafees Ahmed to PhD in TIAC and also appointed Dr. Sadeed Arif as his Supervisor. 

2.	He joined the Institute on 03.03.2015.

3.	The Director, Taxila Institute of Asian Civilization (through Dean concerned) has forwarded (Annexure-I) the name of Dr. Aasim Sajjad Akhtar, Assistant Professor, NIPS as his Co-Supervisor.

4.	C.V. of Co-Supervisor is attached at Annex-II.

5.	The case is placed before the Board for consideration

## Item No.29

### Consideration of the recommendations of the Chairman, Department of Business and Engineering Management Sir Syed CASE Institute of Technology regarding approval of topic of dissertations and name of Supervisors of MS Management and MS Project Management (Fall-2016 & Sprin2017 Batch)								

    The case regarding approval of topic of dissertations and name of Supervisors of MS Management and MS Project Management (Fall-2016 & Sprin2017 Batch) was placed before the Board at its meeting held on 15.01.2020, wherein it was resolved as under:-

 __“The Board discussed the case and referred it to the following Committee for examining it as per rules and policy of QAU. The recommendations will be placed before the AS&RB in its next meeting.__

    1.	Prof. Dr. Nazir Hussain,Director, School of Politics and International Relation 
    
    2.	Prof. Dr. Imtiaz ud Din, Director, Quality Enhancement Cell 
    
2.	In the light of the above decision of the Board, now the  Director, Quality Enhancement Cell has forwarded the case for placing its again before the AS&RB for approval of topic of dissertations and name of Supervisors of the following two Departments:-

    1.	MS Management  (Fall-2016 & Spring-2017 Batch			Annex-I

    2.	MS Project Management (Fall-2016 & Spring-2017 Batch		Annex-II

    3.	The case is again placed before the Board for consideration.

## Item No.30

### Consideration of case forwarded by the Controller of Examination regarding review and re-consideration of the decision of the AS&RB for promotion of Grade-B.							
    
    The Controller of Examinations has forwarded (Annex-I) a case of Mr. Jahagir Pechuho, wherein he intends to round off his marks from 59.8% to 60.

A similar case was placed before the Board at its meeting held on 11.02.2020, wherein it was resolved as under:-

 __“The Board resolved to accept the appeal for promotion of grade-B in respect of Mr. Nazar Hussain, Department of DSS rounding 59.8 to 60%.”__
 
2.	The relevant rules in this behalf are as under:

 __“(d)	Percentage of marks shall be calculated up to three significant figures. If the second fraction after decimal is 4 or less, it will be ignored. However, if the second fraction is 5 or more, it will be taken into account by raising the first fraction to the next higher digit. (Examples: 59.91 through 59.94 will be considered 59.9 while 59.95 through 59.99 will be raised to 60. Third fraction and higher will be ignored).__
 
 __(e)	Candidates securing 80% marks or more in a course shall be given grade ‘A’, 60% to 79.9% grade ‘B’, 50% to 59.9% grade ‘C’ and less than 50% grade ‘F’ in that course. The overall performance of a student shall be graded in the same manner.”__

4.	The Controller of Examination has requested (Annex-II) that this matter needs urgent attention for review/re-consideration of decision of the AS&RB.

5.	The Vice-Chancellor has desired to place the case before the AS&RB for consideration.

## Item No.31
### Consideration of the recommendations of Ex-In-charge, Department of Anthropology regarding appointment of Co-Supervisor in respect of   Ms. Tang Yi, a PhD student in Anthropology				

    The Advanced Studies & Research Board at its meeting held on 13.06.2019 approved the following recommendation of the Admission Committee regarding enrollment of a PhD student from Peking University in Fall semester 2019:-

 __“The Board resolved to allow the placement of Tang Yi in the Department of Anthropology for a period of 8 months on self-funded exchange programe. The Board further asked the Department to allocate co-supervisor (if needed).”__
 
2.	She joined the Department on 10.02.2020.

3.	Now the Ex-In-charge, Department of Anthropology (through Dean concerned) has proposed (herself) as a Co-Supervisor of Ms. Tang Yi, a PhD student in Anthropology (Annexure-I).

4.	The case is placed before the Board for consideration

## Item No.32

###	Consideration of the case regarding restoration of PhD admission of             Mr. Muhammad Zia ul Haq, PhD student in National Institute of Pakistan Studies	.									

    Clause III(a-b-c) of the Regulations relating to re-admission, registration & examination to PhD provides as under:-

 __(a)	A student whose admission is cancelled on grounds other than disciplinary action may be re-admitted in the PhD Programme, subject to the payment of outstanding dues__
 
 __(b)	If the course work and comprehensive examination were passed within five years prior to the cancellation of the admission, full credit may be allowed regarding course work and comprehensive examination as the case may be. In case the admission is sought after the lapse of five year from the date of passing the course work and comprehensive examination the departmental PhD Admission Committee may determine the course(s) to be re-done as well as its recommendations about the comprehensive examination__
 
 __(c)	If a student who is re-admitted to PhD program and had previously spent the minimum period of three years as a PhD student, he/she may be allowed to submit the thesis after six months from the date of his/her re-admission.__

2. The Advanced Studies & Research Board at its meeting held on 30.09.2019, approved the cancellation of admission of Mr. Muhammad Zia ul Haq,  a PhD student in NIPS.

3.	 An application submitted to the Vice-Chancellor in respect of Mr. Muhammad Zia ul Haq, a PhD student in Pakistan Studies regarding restoration of his PhD admission. Detail is available at Annexure-I

4.	The Vice-Chancellor has desired to place the case before AS&RB for consideration  

## Item No.33

###	Consideration of a  request forwarded by Controller Examination regarding remit the fine on late submission of thesis in respect of Mr. Muhammad Aslam khan, a student of Biotechnology								
 
    The Controller of Examinations has forwarded an application submitted by Mr. Muhammad Aslam Khan M.Phil student, Department of Biotechnology regarding remit the fine on late thesis submission. All the details relating to the said case is available at (Annex-I). 

2. The case is placed before the AS&RB for consideration.

## Item No.34

###	Consideration of the recommendations of the Chairperson, Department of Pharmacy regarding appointment of Co-Supervisor in respect of                    Ms. Asma Nawaz, a PhD student in Pharmacy				

    The Advanced Studies & Research Board at its meeting held on 30.02.2016, approved the admission/registration of Ms. Asma Nawaz to PhD in Pharmacy and also appointed Dr. Ahmad Khan as her Supervisor. 

2.	She joined the Department on 15.02.2016.

3.	The Board at its meeting held on 01.10.2018, approved the following title of her thesis and Synopsis:-

 __“Identifying and evaluating control mechanisms for illicit prescription drug markets by focusing on consumption of main abuse potential prescription drugs”.__ 

4.	The Chairperson, Department of Pharmacy (through Dean concerned) has forwarded (Annexure-I) the name of Dr. Tahir Mehmood, Associate Professor School of Natural Sciences (SNS) National University of Sciences and Technology (NUST, Islamabad as her Co-Supervisor.

5.	C.V. of Co-Supervisor is attached at Annex-II.

6.	The case is placed before the Board for consideration 


## Item No.35

###	Consideration of the recommendations of the Chairperson, Department of Microbiology regarding approval Re-admission test, field & name of Supervisor in respect of Mr. Muhammad Yousaf Khan, Department of Microbiology									

    Mr. Muhammad Yousaf Khan applied for admission to PhD in Microbiology but the Departmental Admission Committee declared as ineligible because of 3.7 CGPA           out of 5. 

2. The AS&RB at its meeting held on 30.09.2019, while consideration the request to recalculate CGPA and relief in the admissions of PhD Program in respect of PhD candidates who could not secure their admissions in Fall Semeester-2019 resolved as under:-

 __“The Board resolved to approve the admission into PhD Programs in respect of all those candidates who have secured 3.7 CGPA out of 5 in M.Phil at QAU and who have been recommended by the respect Admission Committee of the Departments/Institutes/Centres/Schools”__ 

3. Now, in the light of the above decision of the Board, the Chairperson, Department of Microbiology has intimated (Annexure-I) through Dean concerned that the Departmental Admission Committee recommended the admission/ registration of Muhammad Yousaf Khan PhD. in Microbiology and also proposed the name of Dr. Arshad Hussain as Supervisor and Dr. Muhammad Imran (Associate Professor) as his   Co-Supervisor.      

4. The prescribed qualifications for admission/registration to Ph.D. are as under:- 

 __a)	To be eligible for admission to Ph.D. a candidate shall possess an M.Phil degree or its equivalent in a relevant subject from a recognized university.__
 
 __b)	A college or university teacher or a member of the research staff of a research organization who holds an M.A./M.Sc. degree but has shown undoubted promise for research may also be considered for admission to Ph.D.__

5. The prescribed qualifications for admission to PhD as per HEC letter                No.1-4(MS/PhD)/QAD/HEC/2018/86/293, dated December, 03,2018  regarding minimum criteria for admission in PhD or equivalent program, adopted by the University in its AS&RB meeting held on 06.12.2018  are as under:-	

 __a)	For admission into the PhD Minimum CGPA 3.0 (out of 4.0 in the Semester System) or First Division (in the Annual System) in MPhil/MS/Equivalent degree is required.__

 __b)	If the Test is not available in NTS subject list, then a University Committee consisting of at least 3 PhD faculty members in the subject area will prepare the Test at par with GRE Subject Test and qualifying score for this will be 70% score.__
 
6. Now the Chairperson, Department of Microbiology has forwarded an appeal for   admission test, field of Research and name of their Supervisors (Annexure-I) in respect Mr. Muhammad Yousaf Khan PhD student Department of Microbiology for consideration of the Board. 

7.	The case is placed before the Board for consideration.

## Item No.36

###  	Consideration of a case forwarded by the Controller of Examinations regarding waive off of late thesis submission fee in respect of                 Ms. Samreen Sadiq, M.Phil student Department of Microbiology.		

    The Controller of Examinations has forwarded (Annex-I) an application submitted by Ms. Samreen Sadiq M.Phil student, Department of Microbiology regarding waive off of late thesis submission fee.  

2. 	The brief history of the case is as under:-

__The Advanced Studies & Research Board in its meeting held on 03.05.2019 resolved to approve the request of Ms. Samreen Sadiq, M.Phil student, Department of Microbiology to submit her thesis subject to condition that her request was routed through the Chairperson of the Department and Dean of the Faculty. The student would have to deposit a fine as per rules (Annex-II).__ 

The decisions of the Advanced Studies and Research Board regarding fixation of time frame for submission of Hard Bind copies of the Dissertations after the Viva-Voce and corrections made by the External Examiners for the students registered in M.Phil program are in the following three meetings:

AS & RB 255 Meeting held on 16-08-2011
 __“The board resolved fix four months’ time for submission of Hard bind copies of the Dissertations after the Viva-Voce and corrections suggested by the external examiners for the students registered in M. Phil. Program.”__
 
AS & RB 262 Meeting held on 12th& 19th March-2012
 __“The board further resolved that in such cases in future if the student fails to deposit the thesis within four months of the viva-voce he/she will be asked to deposit fine as follows: a: within four-five months of the viva-voce: Rs. 5000/- b: within 5-6 months Rs. 10,000/-. Thereafter too the fine would continue to increase at the rate of Rs.5000/- month.”__
 
AS & RB 265 Meeting held on 14-06-2012
 __“The board further resolved that in such cases in future if the student fails to submit the thesis within four months of the viva-voce he/she will be asked to deposit fine as follows: a: within four-five months of the viva-voce: Rs. 5000/- b: within 5-6 months Rs. 10,000/-. Thereafter too the fine would continue to increase at the rate of Rs.5000/- month. However, the student shall not be allowed to submit the thesis after lapse of one year in any circumstances.”__
 
3.	The Controller office has stated that:-
“The office has examined the case in the light of above reproduced decisions of the AS&RB and found that the viva-voce examination was held on 12.03.2012 and final thesis and award list of viva voce examination was received in the Controller of Examinations office on 26.07.2019 after the lapse of 06-years and 05 months and the amount of the fine is Rs. 3,65,000/- @ 5000/- per month for 06-years and 01 month in the light of AS&RB decision.”

4.	The Dean, Faculty of Biological Sciences has desired to place the case before the AS&RB for consideration

## Item No.37

###  	Report of the action of the Vice-Chancellor regarding award of PhD Degrees in respect of ten (10) PhD students of various Department School/Centre.									

    Advanced Studies & Research Board at its meeting held on 30-07-2008, authorized the Vice-Chancellor to approve the cases regarding award of PhD degree to the successful students. The decision of the Board is quoted below:-

 __“The Board considered the recommendation of the Acting Dean, Faculty of Natural Sciences regarding authorization to the Vice-Chancellor for award of Ph.D. degree to the successfully students in future and report to the Board in the next meeting for information/confirmation”.__
 
2.	The Assistant Controller has forwarded (Annexure-I ) the case of the following ten (10) PhD students of various Department/School/Centre, who have been awarded the degrees by the Vice-Chancellor, in accordance with the above quoted decision of the AS&RB:-

    S.N0.	Name of Students	Department/School/Centre
  
    1.		Mr. Noor Muhammad	Mathematics
    2.		Ms. Humara Sardar	Mathematics
    3.		Mr. Wajid Hussain Joyia	Physics
    4.		Mr. Asad Muhammad Iqbal	Physics
    5.		Mr. Naveed Iqbal	Earth Sciences
    6.		Mr. Sajjad Khan	Earth Sciences
    7.		Ms. Sana Riaz	Biochemistry
    8.		Ms. Aisha Siddiquah	Biotechnology
    9.		Ms. Mehreen Zaka	Biotechnology
    10.		Ms. Fatima Khalid	Plant Sciences

3.	The case is reported to the Board for information/confirmation.

## Item No.38

###	Report of the action of the Dean, Faculty of Biological Sciences regarding approval of title of dissertations and name of Supervisors in respect of  M.Phil students in Biotechnology						

    The Advanced Studies & Research Board at its meeting held on 01.10.2018, approved the admission/registration of thirteen (13) students of M.Phil in Biotechnology 

2.	Now the Dean, Faculty of Biological Sciences has approved (Annexure-I) the title of dissertations and name of their Supervisors.

3.	The case is placed before the Board for confirmation/consideration.


## Item No.39

### Report of the action of the Dean, Faculty of Social Sciences regarding approval of title of dissertations and name of Supervisors in respect of  M.Phil students in School of Economics					

    The Advanced Studies & Research Board at its meetings held on 13.02.2017 & 28.02.2018, approved the admission/registration of Ten (10) students of M.Phil in School of Economics. 

2.	Now the Dean, Faculty of Social Sciences has approved (Annexure-I) the title of dissertations and name of their Supervisors.

3.	The case is placed before the Board for confirmation/consideration. 


## Item No.40

###	Report of the action of the Dean, Faculty of Social Sciences regarding approval of title of dissertations and name of Supervisors in respect of  M.Phil students in Centre of Excellence in Gender Studies 			

    The Advanced Studies & Research Board at its meeting held on 19.02.2019, approved the admission/registration of Ten (10) students of M.Phil in Centre of Excellence in Gender Studies. 

2.	Now the Dean, Faculty of Social Sciences has approved (Annexure-I) the title of dissertations and name of their Supervisors.

3.	The case is placed before the Board for confirmation/consideration.

## Item No.41

### Report of the action of the Dean, Faculty of Social Sciences regarding approval of title of dissertations and name of Supervisors in respect of  M.Phil students in Sociology							

    The Advanced Studies & Research Board at its meeting held on 01.10.2018, approved the admission/registration of sixteen (16) students of M.Phil in Sociology. 

2.	Now the Dean, Faculty of Social Sciences has approved (Annexure-I) the title of dissertations and name of their Supervisors.

3.	The case is placed before the Board for confirmation/consideration.

## Item No.42

### Report of the action of the Deans of Faculties regarding approval of titles of dissertations and names of Supervisors in respect of M.Phil students various Departments/Institutes/Schools/Centres.				

    Following M.Phil students from the various Departments/ Institutes/Schools/Centres have requested for approval of titles of dissertations and names of Supervisors duly recommended by the Chairpersons/Directors. The requests have been approved by the concerned Deans:-

Department of Earth Sciences (Annexure-I)

    S.No	Name of student & DOJ	Admission approved	Title of dissertation	Supervisor
    1.	Noor ul Ain Abbasi 12.03.2018	28.02.2018	Flood Hazard Modelling and Inundation Mapping of Korang River, Islamabad Capital Area	Prof. Dr. M. Gulriaz Akhter
    Already approved on 330-Meeting dated 19.04.2019

Department of Electronics (Annexure-II

    S.No	Name of student & DOJ	Admission approved	Title of dissertation	Supervisor
    1.	Shafiq-ur-Rehman 12.03.2018	28.02.2018	Wideband Delta-Sigma Modulator For High Resolution Applications	Dr. Arshad Hussain 
    Already approved on 03.05.2019

School of Politics and International Relations (Annexure-III)

    S.No	Name of student & DOJ	Admission approved	Title of dissertation	Supervisor
    1.	Mr. Ishfaque Ahmed Soomro Spring 2016	05.09.2016	Etheric conflict and International Security: A Case Study of Myanmar 	Dr. Farhan Hanif Siddiqui
    Already approved on 17.11.2017

Area Study Centre for Africa, North & South America (Annex-IV)

    S.No	Name of student & DOJ	Admission approved	Title of dissertation	Supervisor
    1.	Nushrah Arshad 10.10.2018	01.10.2018	Narrative Constructions of Feminine Queer Identities in Young Adult Literature from the Stonewall Riots to the Pride Month	
    Dr. Ayesha Siddiqa

    2.	Jawad Shah 15.10.2018		“Freedom From” and Freedom To”: Quest for the American Dream in F. Scott Fitzgerald’s The Great Gatsby and Salman Rushdie’s The Golden House	

    3.	Spugmay Ali 15.10.2018		Art and Literature: A Neuroscientific Study of the Works of William Carols Williams and Claude Monet	

2.	The case is reported to the Board.
 
## Item No.43

###	Report of the action of the Deans of Faculties regarding approval of titles of theses and Synopses in respect of PhD students various Departments/Institutes/Schools/Centres.					

    Following PhD students from the various Departments/ Institutes/Schools/Centres have requested for approval of titles of theses and Synopses duly recommended by the Admission Committee. The requests have been approved by the concerned Deans:

Department of Mathematics (Annex-I)

    S.No	Name of student	Admission/Supervisor approved	Title and Synopsis	Date of joining
    1.	Muhammad Tanveer	05.09.2016 Dr. Asif Ali                                 	Design of Symmetric Key Cryptosystems Based on Chaos and Algebra: Applications in Image Processing	05.10.16

    2.	Jawad Ali	23.08.2017 Dr. Zia Bashir	A study on multi-criteria group decision making techniques based on fuzzy and quantitative information	12.09.17

Department of Electronics (Annex-II)

    S.No	Name of student	Admission/Supervisor approved	Title of thesis	Date of joining
    1.	Adil Qayyam Bhatti	13.02.2017 Prof. Dr. Qaisar A. Naqvi 	Study of Optical Properties of Noninteger  Dimensional Nonlinear Medium	03.03.17

    2.	Ghulam Raza	23.08.2017 Dr. Muhammad Aqueel Ashraf	Design and Development of Opto-Electronics System for Remote Sensing of Troposphere	12.09.17

Department of Computer Sciences (Annex-III)

    S.No	Name of student	Admission/Supervisor approved	Title and Synopsis	Date of joining
    1.	Muhammad Fahad Khan	19.09.2014 Dr. Khalid Saleem	Nonlinear Block Cipher Primitive Using True Random Numbers	03.10.14

Department of Plant Sciences (Annex-IV)

    S.No	Name of student	Admission/Supervisor approved	Title and Synopsis	Date of joining
    1.	Saman Maqbool	19.02.2019 Dr. Awais Rasheed	Genomics for root System Architecture and Stomatal Traits in Bread Wheat	26.09.19

Department of Environmental Sciences(Annex-V)

    S.No	Name of student	Admission/Supervisor approved	Title and Synopsis	Date of joining
    1.	Muhammad Saeed	23.08.2017 Prof. Dr. Riffat Naseem Malik	Arsenomics of bread wheat (Triticum aestivum L.) and rice (Oryza Sativa L.): To decipher qualitative and quantitative impact of As on grain yield	25.09.17

Department of Sociology (Annex-VI)

    S.No	Name of student	Admission/Supervisor approved	Title of thesis	Date of joining
    1.	Aftab Ahmed	19.02.2019 Dr. Sarfraz Khan	Ageing and Social Exclusion in Pakistan	22.02.19
    2.	Muhammad Farooq Ahmad		Socio-Economic and Psychological Wellbeing of Elderly People in Families of Migrants: A Case Study of Tehsil Kallar Syedan, Pakistan	22.02.19

School of Economics (Annex-VII)

    S.No	Name of student	Admission/Supervisor approved	Title of thesis	Date of joining
    1.	Muhammad Zamir Khan	30.01.2014 Dr. Farzana Naheed Khan	Empirical Analysis of Transport Demand and Efficiency of Deficiency of Different Transport Modes in Pakistan	17.02.14
    2.	Shafqut Ullah	30.01.2014 Dr. Tahir Mehmood	Energy Rebound, Intensity, and Output Effect: An Aggregate and Disaggregate Analysis of Pakistan	04.02.14

2.	The case is reported to the Board.

## Item No.44

###	Consideration of the recommendations of the Chairperson, Department of Bioinformatics regarding approval of list of Foreign Referee for PhD thesis evaluation.								
	
    The Chairperson, National Centre for Bioinformatics through Dean, Faculty of Biological Sciences has forwarded the list of Foreign Referee for PhD thesis evaluation along-with the duly filled Performa Annex-I for approval.

2.	The case is placed before the Board for consideration.

## Item No.45

###	Consideration of the recommendations of the Chairperson, Department of Bioinformatics regarding approval of list of Local Experts for M.Phil and PhD thesis evaluation								
		
    The Chairperson, Department of Bioinformatics through Dean concerned has forwarded the lists of Local Experts for M.Phil and PhD thesis evaluation	along-with duly filled Performas. 		

2.	Copies of the letter of the Chairperson along-with the list of examiners are available at Annexure-I.

3.	The case is placed before the Board for consideration.
 
## Item No.46 

### Consideration of the recommendations of the Chairpersons of various Departments regarding grant of extension (beyond the normal period of 7 years) in respect PhD students.								

    The Chairpersons of various Departments have forwarded the request regarding grant of extension (beyond the normal period of 7 years) in respect of following students. The bio-data of students is as under:-	

    S.No	Name of student	Date of admission 	Date of joining	Date of approval of Sup. & title 	Name of Supervisor	Department/ Centre	Date of approval and previous extension upto	Now request for Extension upto 	Annex
    1.		Mr. Qualab Naveed	04.02.2013	14.02.2013	04.02.2013 08.09.2014	Dr. Rani Faryal	Microbiology	-	For one semesters	I
    2. Ms. Sumaira Mazhar 	08.02.2012	14.02.2012	08.02.2012	Dr. M. Ilyas Sarwar	Chemistry	-	For One year II

2.	The case is placed before the Board for consideration.

## Item No.47

###	Consideration of the recommendations of the Chairpersons/Directors of various Departments/Institutes/Schools/Centres regarding cancellation of admission/registration in respect of PhD students.						

    The Chairpersons/Directors of various Departments/Institutes/Schools/Centres through Dean concerned have forwarded the requests regarding cancellation of admission/registration in respect of the following students:- 

    S.No.	Name of student	Date of admission 	Date of joining	Date of approval of Supervisor  	Name of Supervisor	Department 	Annexure

    1.	Mr. Syed Zawar Hussain Shah 	20.02.2015	02.03.2015	20.02.2015	Dr. Azhar Iqbal	Chemistry	I 

    2.	Mr. Mahboob-ur-Rehman  	08.02.2012	13.02.2012	08.02.2012	Dr. Syed Ahmad Tirmizi	Chemistry	II

    3.	Mr. Muhammad Ammar Zahid	14.03.2017	-	08.02.2012	Dr. Javaria Qazi	Biotechnology	III

4.	The case is placed before the Board for consideration.


## Item NO. 48

###	Consideration of a case regarding grant of permission for revising her percentage that enable to submit her thesis in respect of  Ms. Zaib-un Nisa, student of M.Phil in (SPIR).										

    An application submitted  to the Vice-Chancellor in respect of  Ms. Zaib-un Nisa, student of M.Phil in (SPIR) regarding grant of permission for revising her percentage that enable to submit her thesis (Annex-I) and intimated that:-

 __“With, all due respect, it is stated that, I, Zeb-un-Nisa of M.Phil IR 2nd semester, from school of politics and International Relations has undergone some serious health issues, due to which, my performance in the semester, didn’t. go very sound. I assure of a very fruitful comeback in my academics, if I am given a chance”.__

2.	The Vice-Chancellor has desired to place the case before AS&RB for consideration  

## Item No.49

### Consideration of a case relating to guidelines for formatting of PhD thesis and MPhil dissertation									

    To avoid unnecessary use of paper, it is proposed to set the following guidelines for formatting of PhD thesis and MPhil dissertation with the approval of the ASRB members:
 
    i.	Line Spacing: The thesis/dissertation text should be 1.5 spaced lines
    
    ii.	Printing: Thesis/Dissertation must be printed on both sides of the pages
 
2.	At the moment, the university rules for thesis/dissertation’s formatting are silent. 
3.	Therefore, the case is placed before the Board for consideration.

## Item No.50

###	Consideration of the case forwarded by the  Chairperson, National Center Bioinformatics regarding request for the position of Post-doc  in respect of Dr. Saneela Anwar, PhD in National Center Bioinformatics.

    The Chairperson, National Center Bioinformatics through Dean, Faculty of Biological Sciences has forwarded the case regarding position of Post-doc  in respect of Dr. Saneela Anwar, PhD in National Center Bioinformatics intimated Annex-I that:-

 __I am Dr. Saneela Anwar, I did my Ph.D. (28/09/2017) in Bioinformatics (Functional Genomics) from National Center Bioinformatics, Quaid-i-Azam University, Islamabad. I also served as an Assistant Professor on IPFP bases in International Islamic University, Islamabad from 17-08-2018 to 16-08-2019.__
 
 __Now I want to apply for the position of Postdoc in NCB,                           Quaid-i-Azam University under the supervision of Dr. Amir Ali Abbasi (Associate Professor, NCB) in a project related to functional validation of computationally predicted human limbs specific enhancers. Currently, I am not engaged in any other job (teaching/research etc.) and therefore will commit myself fully in postdoc research project.__ 

 __I would be greatly obliged in you consider my application positively. For your kind consideration my CV and other required documents are attached.”.__

2.	The Dean, Faculty of Biological Sciences has recommended to place the case before the Advanced Studies and Research Board. 

3.	The C.V. of Dr. Saneela Anwar, is available at Annex-II. 

4.	The case is placed before the Board for consideration.

 

